github_repos:
  outputs:
    dev:
      dataset: dbt_github_repos
      job_execution_timeout_seconds: 600
      job_retries: 1
      keyfile: service-account.json
      location: US
      method: service-account
      priority: interactive
      project: github-repos-data-exploration
      threads: 1
      type: bigquery
  target: dev
