version: 2

sources:
  - name: core
    database: bigquery-public-data
    schema: github_repos

    tables:
      - name: files
      - name: contents

models:
  - name: repos__file_contents_last_updated
    description: This model joins the files and contents tables with their last updated date
    columns:
      - name: repo_name
        description: Repository name
        tests:
          - not_null
      - name: last_updated
        description: Last updated date
        tests:
          - not_null
      - name: path
        description: File path inside the repository
        tests:
          - not_null
      - name: content
        description: File content
      - name: binary
        description: Whether the file is a binary
        tests:
          - not_null

  - name: sample_repos__file_contents_last_updated
    description: Sample of the repos__file_contents_last_updated table
    columns:
      - name: file_id
        description: Unique file ID
        tests:
          - unique
          - not_null
      - name: repo_name
        description: Repository name
        tests:
          - not_null
      - name: last_updated
        description: Last updated date
        tests:
          - not_null
      - name: path
        description: File path inside the repository
        tests:
          - not_null
      - name: content
        description: File content
      - name: binary
        description: Whether the file is a binary
        tests:
          - not_null
