
name: 'github_repos_data_exploration'
version: '1.0.0'
config-version: 2

profile: 'github_repos'

model-paths: ["models"]
test-paths: ["tests"]
macro-paths: ["macros"]

clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

models:
  github_repos_data_exploration:
    staging:
      +materialized: view
    core:
      +materialized: table
